github: [StorytellerCZ, copleykj, mitar, zimme, wreiske]
ko_fi: storyteller
custom: ["https://www.subscribestar.com/storyteller", "https://www.paypal.me/JDvorak", "https://www.buymeacoffee.com/storyteller", "https://paypal.me/wreiske"]
